[package]
name = "std_utils"
description = "Standard utilities for Rust"
homepage = "https://github.com/LeviLovie/std_utils"
repository = "https://github.com/LeviLovie/std_utils"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
tracing = "0.1.41"
